/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.codebits.softwareninja;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int black=0x7f040006;
        public static final int blue=0x7f040002;
        public static final int blue_green_grey=0x7f04000f;
        public static final int blue_light=0x7f04000e;
        public static final int cornflowerblue=0x7f040011;
        public static final int dark_gray=0x7f04000b;
        public static final int darkgrayfaded=0x7f040005;
        public static final int darkred=0x7f040010;
        public static final int emeraldgreen=0x7f040012;
        public static final int gray=0x7f040004;
        public static final int gray1=0x7f040008;
        public static final int gray2=0x7f040009;
        public static final int gray3=0x7f04000a;
        public static final int green=0x7f040001;
        public static final int light_blue=0x7f040007;
        public static final int red=0x7f040000;
        public static final int white=0x7f040003;
        public static final int yellow1=0x7f04000c;
        public static final int yellow2=0x7f04000d;
    }
    public static final class drawable {
        public static final int barra=0x7f020000;
        public static final int bck=0x7f020001;
        public static final int botao_cancel_green=0x7f020002;
        public static final int botao_cancel_red=0x7f020003;
        public static final int botao_ciclo_green=0x7f020004;
        public static final int botao_ciclo_red=0x7f020005;
        public static final int botao_exp_green=0x7f020006;
        public static final int botao_exp_red=0x7f020007;
        public static final int botao_if_green=0x7f020008;
        public static final int botao_if_red=0x7f020009;
        public static final int botao_print_green=0x7f02000a;
        public static final int botao_print_red=0x7f02000b;
        public static final int botao_start_green=0x7f02000c;
        public static final int botao_start_red=0x7f02000d;
        public static final int ciclobtn=0x7f02000e;
        public static final int endbtn=0x7f02000f;
        public static final int expbtn=0x7f020010;
        public static final int fail=0x7f020011;
        public static final int greenballon=0x7f020012;
        public static final int greyballon=0x7f020013;
        public static final int ic_action_search=0x7f020014;
        public static final int ic_launcher=0x7f020015;
        public static final int ifbtn=0x7f020016;
        public static final int lixo_fechado=0x7f020017;
        public static final int printbtn=0x7f020018;
        public static final int run_button=0x7f020019;
        public static final int sensei=0x7f02001a;
        public static final int startbtn=0x7f02001b;
        public static final int success=0x7f02001c;
    }
    public static final class id {
        public static final int ContextToolboxView=0x7f080002;
        public static final int SurfaceView01=0x7f080001;
        public static final int addExistingVariableToCond=0x7f08002a;
        public static final int addExistingVariableToExpr=0x7f080027;
        public static final int assignedVariableType=0x7f080022;
        public static final int assignment=0x7f08000e;
        public static final int button1=0x7f08000f;
        public static final int challengebtn=0x7f080012;
        public static final int chooseVariables=0x7f080026;
        public static final int closeToolboxBtn=0x7f080005;
        public static final int closebtn=0x7f080010;
        public static final int conditionLabel=0x7f080028;
        public static final int cyclobtn=0x7f080009;
        public static final int editNodeLayout=0x7f080004;
        public static final int endbtn=0x7f08000b;
        public static final int epressionLayout=0x7f080023;
        public static final int errorview=0x7f08001b;
        public static final int expbtn=0x7f080007;
        public static final int expressionLabel=0x7f080024;
        public static final int freeforallbtn=0x7f080015;
        public static final int identifier=0x7f080018;
        public static final int ifbtn=0x7f080008;
        public static final int imageView1=0x7f08001c;
        public static final int imageView2=0x7f080019;
        public static final int imageView3=0x7f080011;
        public static final int imageView4=0x7f08000c;
        public static final int innerEditLayout=0x7f08001e;
        public static final int inputCondition=0x7f080029;
        public static final int inputExpr=0x7f080025;
        public static final int main=0x7f080000;
        public static final int menu_settings=0x7f08002b;
        public static final int nodeName=0x7f080003;
        public static final int printbtn=0x7f08000a;
        public static final int puzzleonebtn=0x7f080013;
        public static final int puzzletwobtn=0x7f080014;
        public static final int removeParameterBtn=0x7f080016;
        public static final int startbtn=0x7f080006;
        public static final int textView1=0x7f08000d;
        public static final int textView2=0x7f08001d;
        public static final int textView3=0x7f08001a;
        public static final int type=0x7f080017;
        public static final int variableAssignedName=0x7f080021;
        public static final int variableLabel=0x7f080020;
        public static final int variableLayout=0x7f08001f;
    }
    public static final class layout {
        public static final int activity_sand_box=0x7f030000;
        public static final int assignment=0x7f030001;
        public static final int main=0x7f030002;
        public static final int parameter_item_list=0x7f030003;
        public static final int result_fail=0x7f030004;
        public static final int result_success=0x7f030005;
        public static final int toolbox_expr_node=0x7f030006;
        public static final int toolbox_if_node=0x7f030007;
    }
    public static final class menu {
        public static final int activity_sand_box=0x7f070000;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int assignment=0x7f05000d;
        public static final int challenge=0x7f050009;
        public static final int close=0x7f05000e;
        public static final int complement=0x7f050005;
        public static final int failure=0x7f050007;
        public static final int freeforall=0x7f05000b;
        public static final int hello_world=0x7f050001;
        public static final int menu_settings=0x7f050002;
        public static final int programninja=0x7f050008;
        public static final int puzzle_one=0x7f05000a;
        public static final int puzzle_two=0x7f05000c;
        public static final int success=0x7f050004;
        public static final int title_activity_sand_box=0x7f050003;
        public static final int tryagain=0x7f050006;
    }
    public static final class style {
        public static final int AppTheme=0x7f060000;
    }
}
